### ISSUE TITLE
Parsing issue: space-separated AS list

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#47] opened 2018-07-06 14:57 UTC
```
as-set:         AS-MQCUSTOMERS
descr:          MarquisNet LLC
descr:          7185 Pollock Drive
descr:          Las Vegas, NV 89119
descr:          US
tech-c:         ENGIN16-ARIN
admin-c:        ENGIN16-ARIN
members:        AS10270 AS36286 AS20104 AS23521 AS22837 AS13446 AS27193
mnt-by:         MNT-MARQU-3
changed:        engineering@marquisnet.com 20100721
source:         ARIN
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: Invalid AS number AS10270 AS36286 AS20104 AS23521 AS22837 AS13446 AS27193: number part is not numeric
ERROR: Invalid set AS10270 AS36286 AS20104 AS23521 AS22837 AS13446 AS27193: component AS10270 AS36286 AS20104 AS23521 AS22837 AS13446 AS27193 is not a valid AS number nor a valid set name
```

This object is invalid, and we parse members, being a lookup attribute. It is also required for as-set resolving.

**Comment by job** [comment] 2018-08-06 11:29
duplicate of https://github.com/irrdnet/irrd4/issues/51

**Closed by job** 2018-08-06 11:29 UTC
