### ISSUE TITLE
Parsing issue: Invalid route-set members in RIPE

### ISSUE THREAD

**Issue by mxsasha** [irrdnet/irrd4#54] opened 2018-07-06 15:22 UTC
```
rtr-set:        rtrs-stanbicbank-uganda
members:        196.8.207.0/24
members:        196.8.208.0/24
descr:          STANBIC BANK UGANDA
tech-c:         DUMY-RIPE
admin-c:        DUMY-RIPE
mnt-by:         RIPE-NCC-LOCKED-MNT
created:        2014-05-12T14:46:40Z
last-modified:  2016-04-25T13:15:17Z
source:         RIPE
remarks:        ****************************
remarks:        * THIS OBJECT IS MODIFIED
remarks:        * Please note that all data that is generally regarded as personal
remarks:        * data has been removed from this object.
remarks:        * To view the original object, please query the RIPE Database at:
remarks:        * http://www.ripe.net/whois
remarks:        ****************************
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: Invalid DNS name: 196.8.207.0/24
ERROR: Invalid DNS name: 196.8.208.0/24
```

(Members should be other rtr-set names, an inet-rtr name or an IPv4/IPv6 address.

**Comment by job** [comment] 2018-08-06 10:49
Duplicate of https://github.com/irrdnet/irrd4/issues/65

**Closed by job** 2018-08-06 10:49 UTC
